[tool.poetry]
name = "gym-cartpole-swingup"
version = "0.0.9"
description = "A simple, continuous-control environment for OpenAI Gym"
authors = ["Ângelo Gregório Lovatto"]

[tool.poetry.dependencies]
python = ">=3.7"
gym = "^0.17.2"

[tool.poetry.dev-dependencies]
tox = "^3.15.2"
mypy = "^0.780"
torch = "^1.5.0"
pylint = "^2.5.3"
black = "^19.10b0"
ipython = "^7.15.0"
pre-commit = "^2.4.0"
flake8 = "^3.8.2"
pip = "^20.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
